# Site

name: "Vida De Avion"

title: "title title title"

description: "Even James Dean couldn't escape the allure."

logo: 'assets/images/logo.png'

favicon: 'assets/images/logo.png'

baseurl: /

google_analytics: 'UA-xxxxxxxx-1'

disqus: 'disabled'

mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]

permalink: /:categories/:title/

email: the.software.shinobi@gmail.com

##
## Authors
##

authors:


  vidadeavion:
    name: mateo
    display_name: mateo
    avatar: 'assets/images/softwareshinobi.jpg'
    email: the.software.shinobi@gmail.com
    web: https://vidadeavion.online
    twitter: https://twitter.com/vidadeavion
    description: "Even James Dean couldn't escape the allure."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
##
## Pagination
##

paginate: 24

paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
